### ISSUE TITLE
CheckSatelliteBuildCompleted retries forever

### ISSUE THREAD

**Issue by henrygrover** [rhtconsulting/miq-RedHat-Satellite6#20] opened 2017-10-24 18:44 UTC
As part of a provision, this step has been retried >1700 times over the course of a day. A timeout should be added to stop retrying if the step takes too long.

**Comment by itewk** [comment] 2017-11-28 13:16
@henrygrover this is a duplicate of https://github.com/rhtconsulting/miq-RedHat-Satellite6/issues/21

**Closed by itewk** 2017-11-28 13:16 UTC
